version: 0.0
os: linux
files:
    - source: /
      destination: /myapp
permissions:
    - object: /myapp/scripts/startApp.sh
      mode: 777
hooks:
    AfterInstall:
        - location: scripts/startApp.sh
          timeout: 300
